name: Go

on:
  push:
    branches:
      - 'master'
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the Docker image
        run: |
         tag=latest
         [[ "$GITHUB_REF" =~ ^refs/tags/ ]] && tag="${GITHUB_REF/refs\/tags\//}"
         docker build . --tag "ghcr.io/carapace-sh/go:${tag}"
         docker push "ghcr.io/carapace-sh/go:${tag}"
